version: "3.2"

services:

  functions-node-18:
    image: functions-node-18
    build:
      context: ..
      dockerfile: ./docker/functions-node-18/Dockerfile
    command: /bin/true

  cosmosdb:
    image: cosmosdb
    env_file:
      - ./environments/generated/env.cosmosdb
    build:
      context: ../docker/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - ${COSMOSDB_PORT}:3000

  storage-account:
    image: azurite
    build:
      context: ../docker/azurite
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  function:
    image: fn
    env_file:
      - ./environments/generated/env.function
    build:
      context: ..
      dockerfile: ./docker/functions/Dockerfile
    ports:
      - ${FUNCTION_PORT}:7071
    links:
      - cosmosdb
      - storage-account
    depends_on:
      - functions-node-18

  testagent:
    image: node:16-alpine@sha256:a1f9d027912b58a7c75be7716c97cfbc6d3099f3a97ed84aa490be9dee20e787
    working_dir: /usr/src/app
    command: tail -f /dev/null # to keep it   up&running
    env_file:
      - environments/generated/env.integration-tests
    volumes:
      - "./:/usr/src/app"
      - "../openapi:/usr/src/openapi"
    depends_on:
      - cosmosdb
      - storage-account
    links:
      - function
