name: "Lint and Link PR title"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    name: Validate PR title And link Jira Issue
    runs-on: ubuntu-22.04
    steps:
      - id: lint
        # from https://github.com/pagopa/link-jira-issue-action
        uses: pagopa/terraform-apply-azure-action@v1.0.0
